apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8080       # Port externe pour accéder au service
      targetPort: 3000 # Port interne de l'application
  type: LoadBalancer   # Expose le service à l'extérieur du cluster
